<?php

/**
 * @file
 * The Social slideshow module.
 */

use Drupal\Core\Template\Attribute;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\paragraphs\Entity\Paragraph;



/**
 * Implements hook_theme().
 */
function social_slideshow_theme() {
  // Paragraphs.
  $theme_templates['paragraph__slideshow__default'] = [
    'base hook' => 'paragraph',
  ];
  $theme_templates['paragraph__slideshow_item__default'] = [
    'base hook' => 'paragraph',
  ];
  $theme_templates['paragraph__slideshow_wide__default'] = [
    'base hook' => 'paragraph',
  ];
  $theme_templates['paragraph__slideshow_wide_item__default'] = [
    'base hook' => 'paragraph',
  ];
  // Fields
  $theme_templates['field__paragraph__field_slideshow_item'] = [
    'base hook' => 'field',
  ];
  $theme_templates['field__paragraph__field_slideshow_wide_item'] = [
    'base hook' => 'field',
  ];
  $theme_templates['field__paragraph__field_slideshow_item_image'] = [
    'base hook' => 'field',
  ];
  $theme_templates['field__paragraph__field_slideshow_title'] = [
    'base hook' => 'field',
  ];
  $theme_templates['field__paragraph__field_slideshow_subtitle'] = [
    'base hook' => 'field',
  ];
  return $theme_templates;
}

/**
 * Prepares variables for the paragraph.
 */
function social_slideshow_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $entity */
  $entity = $variables['elements']['#paragraph'];
  $bundle = $entity->bundle();

  switch ($bundle) {
    case 'slideshow':
      // Add variable
      //kint($variables);
      break;
    case 'slideshow_item':
      // Get the parent paragraph
      $paragraph = $variables['paragraph'];
      $parent = $paragraph->getParentEntity();
      // Define default height
      $variables['slideshow_height'] = '410px';
      if(isset($parent) && isset($parent->field_slideshow_height->value)) {
        $variables['slideshow_height'] = $parent->field_slideshow_height->value . 'px';
      }
      // Add the hero styled image.
      $image_style = 'social_landing_hero';
      $image_field = "field_{$bundle}_image";
      if ($entity->hasField($image_field) && !empty($entity->{$image_field}->entity)) {
        $variables['hero_styled_image_url'] = ImageStyle::load($image_style)
          ->buildUrl($entity->{$image_field}->entity->getFileUri());
      }
      break;

    case 'slideshow_wide_item':
      // Define default height
      $variables['slideshow_height'] = '410px';
      if(isset($parent) && isset($parent->field_slideshow_height->value)) {
        $variables['slideshow_height'] = $parent->field_slideshow_height->value .'px';
      }
      // Add the hero styled image.
      $image_style = 'social_landing_hero';
      $image_field = "field_{$bundle}_image";
      if ($entity->hasField($image_field) && !empty($entity->{$image_field}->entity)) {
        $variables['hero_styled_image_url'] = ImageStyle::load($image_style)
          ->buildUrl($entity->{$image_field}->entity->getFileUri());
      }
      break;
  }
}
